[project]
name = "nexa-auto"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "rich>=14.0.0",
]

[project.scripts]
nexa-auto = "Nexa_Auto.cli:main"
